version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:5.0
    container_name: coderoot_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: coderoot_bot
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - coderoot_network

  # Redis Cache (Optional)
  redis:
    image: redis:7-alpine
    container_name: coderoot_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - coderoot_network

  # CodeRoot Bot Application
  coderoot_bot:
    build: .
    container_name: coderoot_bot
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://admin:password123@mongodb:27017/coderoot_bot?authSource=admin
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - coderoot_network
    # Uncomment if using webhooks
    # ports:
    #   - "8000:8000"

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  coderoot_network:
    driver: bridge