services:
  - type: web
    name: coderoot-bot
    runtime: python3
    plan: starter
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: PRODUCTION_MODE
        value: "true"
      - key: DEMO_MODE
        value: "false"
      - key: LOG_LEVEL
        value: "INFO"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DEFAULT_LANGUAGE
        value: "fa"
      # Add your environment variables here
      # BOT_TOKEN, API_ID, API_HASH, etc. should be added via Render dashboard
    autoDeploy: true
    healthCheckPath: /health