name: Go CI/CD

on:
  push:
    branches: [ "go", "main" ]
  pull_request:
    branches: [ "go", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Verify dependencies
      run: go mod verify
      
    - name: Build
      run: go build -v ./...
      
    - name: Run tests
      run: go test -v ./...
      
    - name: Run go vet
      run: go vet ./...
      
    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
      
    - name: Run staticcheck
      run: staticcheck ./...

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Run Gosec Security Scanner
      uses: securecodewarrior/github-action-gosec@master
      with:
        args: './...'

  docker:
    runs-on: ubuntu-latest
    needs: [test, security]
    if: github.ref == 'refs/heads/go'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -f Dockerfile.liara -t coderoot-bot:${{ github.sha }} .
      
    - name: Test Docker image
      run: |
        docker run --rm -d --name test-bot -p 8080:8080 \
          -e BOT_TOKEN=test \
          -e API_ID=123 \
          -e API_HASH=test \
          -e ADMIN_USER_ID=123 \
          -e MONGO_URI=mongodb://localhost:27017/test \
          -e REDIS_URL=redis://localhost:6379 \
          coderoot-bot:${{ github.sha }} || true
        sleep 5
        docker logs test-bot
        docker stop test-bot || true

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=5m